/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // ─── Stitch M3 Light-Mode Institutional Monochrome ───
        "secondary-container": "#dce2f3",
        "on-secondary": "#ffffff",
        "outline-variant": "#c4c7c7",
        "error-container": "#ffdad6",
        "surface-tint": "#5f5e5e",
        "primary-container": "#1c1b1b",
        "tertiary-fixed": "#e0e2e6",
        "on-secondary-container": "#5e6572",
        "primary-fixed": "#e5e2e1",
        "tertiary-fixed-dim": "#c4c7ca",
        "on-tertiary-fixed": "#191c1f",
        "on-primary": "#ffffff",
        "surface-container-highest": "#e2e2e2",
        "secondary": "#585f6c",
        "surface-container-low": "#f3f3f4",
        "surface-container-lowest": "#ffffff",
        "outline": "#747878",
        "tertiary": "#000000",
        "inverse-primary": "#c9c6c5",
        "on-error-container": "#93000a",
        "inverse-surface": "#2f3131",
        "secondary-fixed-dim": "#c0c7d6",
        "surface-variant": "#e2e2e2",
        "on-error": "#ffffff",
        "surface-bright": "#f9f9f9",
        "secondary-fixed": "#dce2f3",
        "on-tertiary-container": "#818488",
        "on-secondary-fixed-variant": "#404754",
        "on-primary-container": "#858383",
        "primary": "#000000",
        "on-surface-variant": "#444748",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed-variant": "#44474a",
        "surface-dim": "#dadada",
        "tertiary-container": "#191c1f",
        "surface-container-high": "#e8e8e8",
        "on-primary-fixed-variant": "#474646",
        "on-primary-fixed": "#1c1b1b",
        "on-background": "#1a1c1c",
        "on-surface": "#1a1c1c",
        "primary-fixed-dim": "#c9c6c5",
        "surface-container": "#eeeeee",
        "on-secondary-fixed": "#151c27",
        "surface": "#f9f9f9",
        "error": "#ba1a1a",
        "background": "#f9f9f9",
        "inverse-on-surface": "#f0f1f1",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "gutter": "24px",
        "stack-sm": "8px",
        "stack-md": "16px",
        "stack-lg": "32px",
        "section-gap": "120px",
        "margin-desktop": "64px",
        "margin-mobile": "20px",
        "container-max": "1280px",
      },
      maxWidth: {
        "container-max": "1280px",
      },
      fontFamily: {
        "label-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "display": ["Inter", "sans-serif"],
        "stats-tabular": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "mono": ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "label-sm": ["14px", { lineHeight: "20px", letterSpacing: "0.02em", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", letterSpacing: "0", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", letterSpacing: "0", fontWeight: "400" }],
        "display": ["72px", { lineHeight: "72px", letterSpacing: "-0.04em", fontWeight: "800" }],
        "stats-tabular": ["16px", { lineHeight: "24px", fontWeight: "500" }],
        "headline-md": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg-mobile": ["32px", { lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "headline-lg": ["48px", { lineHeight: "52px", letterSpacing: "-0.03em", fontWeight: "800" }],
      },
      boxShadow: {
        "ambient": "0 4px 20px rgba(0, 0, 0, 0.05)",
      },
    },
  },
  plugins: [],
};
